### ISSUE TITLE
When including a query string, KeyNotFoundException is thrown

### ISSUE THREAD

**Issue by Bhavesh-Patel** [oelite/RESTme#21] opened 2016-09-14 15:07 UTC
If a URL contains a query string, i.e. http://localhost/myapi?op=1, then a KeyNotFoundException is thrown

`System.Collections.Generic.Dictionary``2.get_Item(TKey key)
OElite.QueryUtils.ParseIntoQueryString(Dictionary``2 values, Boolean includeQuestionMark)
OElite.Rest.PrepareInjectParamsIntoQuery(String urlPath)`

(I've omitted the irrelevant parts of the callstack, such as TaskAwaiter.)

This issue occurs both when including it as part of the URL and when using OElite.Rest.Add.

The issue is that OElite.QueryUtils.ParseIntoQueryString tries to use the key-value pairs of the Dictionary it's operating on as the key (by using ToString) to the dictionary and this is not going to be a valid key.

This fix is to iterate over Dictionary.Keys. This would also remove the need to call ToString too.

I'll be submitting a pull request with this fix shortly.

**Comment by mleader1** [comment] 2016-09-15 12:39
hi @Bhavesh-Patel  thanks for contributing,  yes that was a dead clear bug which was caused by some refactoring I did the other (Was NameValueCollection in the previous versions)

I'll merge and close the ticket very shortly

**Comment by mleader1** [comment] 2016-09-15 13:16
together with your fix,  here's a line . "index++;"  missing in the old version. I've fixed it now and committed in.

Have committed more code changes just now which can be a new version release, I'll push it to Nuget shortly.

cheers.

**Closed as completed by mleader1** 2016-09-15 13:16 UTC
